### ISSUE TITLE
indexing support

### ISSUE THREAD

**Issue by tekjar** [ezylang/EvalEx#140]
Hi. Is there a way to pass list variables and use indexes?

```
byte[] bytes
new Expression("bytes[1] + bytes[2]")
```

**Comment by uklimaschewski** [comment]
Sorry, there is no support for arrays

**Comment by RobertZenz** [comment]
But could there be? I mean, the though is intriguing but I do not know if the `[]` is already taken with some other operation.

Maybe in the first step just being able to define arrays and use their values might be interesting, something like this:

    Expression expression = new Expression("values[0] + values[1]");
    expression.with("values", new BigDecimal[] { BigDecimal.valueOf("5"), BigDecimal.valueOf("7") });
    // Or with varargs:
    expression.with("values", BigDecimal.valueOf("5"), BigDecimal.valueOf("7"));

Without any sort of "array operations".

**Comment by uklimaschewski** [comment]
Array indexes (like, e.g. value[0]) could be seen as functions. The parser/tokenizer, shunting yard routine and evaluator could be extended to support this with a reasonable efford, I think.
Then even expression like "a + values[x  - 1]" would be possible.
But what would it be good for? You need some more array functionality (loops, assignments, calculations etc.)
Else you can still go with defining a variable for each "array" value, "value1", "value2" etc.
I am not seeing the real need for it right now, but maybe you have some examples?

**Comment by RobertZenz** [comment]
Mh, I ain't got good usage examples without array operations (I didn't think beyond basic math operations, though), I was just throwing ideas into the room. Maybe @tekjar got some.

**Comment by tekjar** [comment]
@uklimaschewski @RobertZenz My use case is also basic math equations but my array size is dynamic. So It's difficult to create variables for each array value

**Comment by uklimaschewski** [comment]
I marked this issue as an enhancement, maybe there will be something in the future. Simple one-dimensional arrays would not be enough, I think.

**Comment by uklimaschewski** [comment]
Arrays now supported in version 3.
