### ISSUE TITLE
isNumber function detects .1.3 as numeric

### ISSUE THREAD

**Issue by HerrDerb** [ezylang/EvalEx#161]
## Issue
The[ `isNumber(String st)`](https://github.com/uklimaschewski/EvalEx/blob/master/src/main/java/com/udojava/evalex/Expression.java#L1090) function in `Expression.class` L50 evaluates a non numeric string ".3.2" to`true`

This is due missing check of multiple occurrence of the `decimalSeperators`

## Expected
".3.4" shall be evaluated to `false` as it is not numeric.

**Comment by dovahkiin98** [comment]
I could say that the best way to detect if .3.2 is a number or not is by using Double.parseDouble.

**Comment by RobertZenz** [comment]
I think the sole problem with it is that one would expect `isNumber(String)` to return `false` if the input is not a correct number.

**Comment by BdasNeves** [comment]
The current solution still have an issue, if we input a string like `"123.123.123"` it will also return `true` when this is an invalid number. 
The evaluation process will detect the problem but will return an `java.lang.NumberFormatException` that can be unexpected to someone that uses this library, I suggest to at least trying to catch this common exceptions and return an `ExpressionException` to avoid surprises.
I also agree with @dovahkiin98 on use the `Double.parseDouble` to detect this cases, something like add this condition on the `isNumber(String)` method:
```
try {
   Double.parseDouble("123.123.123");
} catch (NumberFormatException exception) {
   return false; // Or throw new ExpressionException(exception.getMessage())
}
```

**Comment by uklimaschewski** [comment]
Obsolete with version 3
