### ISSUE TITLE
MathContext of Expression is not available to functions and operators.

### ISSUE THREAD

**Issue by RobertZenz** [ezylang/EvalEx#171]
I've just realized that with the implementation of #144 and #155 a small hole in the API has been opened. For example, a `LazyFunction` implementation defined outside the `Expression` does not have access to the `MathContext` used by the `Expression`.

Adding a getter for the `MathContext` on the `Expression` does not solve that (but it would still be nice to have). Ideally, the `MathContext` would be passed to these implementations, but I'm not very fond of that as it would require to break the API. Alternatively one could make sure that all parameters passed to functions have the correct `MathContext`, so that a function can rely on that. I'm not sure whether that is already happening, but I guess not (as `BigDecimals` can be directly set as parameters).

**Comment by uklimaschewski** [comment]
Yes, I see the problem. The math context should be a parameter to the `eval` methods of `LazyFunction` and `LazyOperator`. This is a similar problem like the evaluation context you were aiming at.

**Comment by RobertZenz** [comment]
That would mean API breakage, though, which I'm not too keen about it. But if you're okay wit it I'd rework that.

**Comment by uklimaschewski** [comment]
Obsolete with version 3, expression with configuration are now passed to operators and functions.
