### ISSUE TITLE
Various built-in functions are not exact.

### ISSUE THREAD

**Issue by RobertZenz** [ezylang/EvalEx#207]
Various built-in functions are not exact and rely on doubles. If possible these should be swapped to `BigDecimal` implementations.

I'm not sure where to get those, though. It's just something that I just noticed.

**Comment by RobertZenz** [comment]
[big-math](https://github.com/eobermuhlner/big-math) seems to implement these functions already, but depending on it doesn't seem to be a very good option.

Everybody can fix this, though, by overriding the functions in the `Expression` after it is being created. I'm not sure how to approach this. The big-math library is MIT licensed, theoretically the source could be embedded, but depending on it would be nicer. But I'm not sure if a dependency is something you want.

**Comment by uklimaschewski** [comment]
FYI: Just started working on an add-on library that replaces and extends the current implementations.

**Comment by uklimaschewski** [comment]
I have just released the first version of the EvalEx big-math extension.
See the announcement here: https://github.com/ezylang/EvalEx/discussions/335
