### ISSUE TITLE
Sub IF evaluate even if in evaluate false side

### ISSUE THREAD

**Issue by laurentyhuel** [ezylang/EvalEx#210]
Hello,

I meet an issue with EvalEx

Let us look at a concrete example:
```
IF ( a = 0, 1, IF (2/a > 1, 2, 3))
```

When a=0, the 2nd IF condition is evaluated and it crash with a division by 0, as the 2nd IF, in this case, is in the false result of the 1rst IF.

**Comment by RobertZenz** [comment]
This might be related to #194.

**Comment by laurentyhuel** [comment]
Yes it's seems to be same problem.

I have a look at https://github.com/gnembon/carpetmod/blob/5ec533ff6a158015bc8cdc3da028238ea6aa1ba4/src/main/java/carpet/script/Expression.java#L1353 but there's lot of changes and some breaking change with existing public method signature.

For instance, in EvalEx:
```
public Expression setVariable(String variable, BigDecimal value) {...}
public Expression setVariable(String variable, LazyNumber value) {...}
public Expression setVariable(String variable, String value) {...}
```
And in gnembon version:
```
public Expression setVariable(String variable, Value value) {}
public Expression setVariable(String variable, LazyValue value) {}
```

What do you suggest ?

**Comment by RobertZenz** [comment]
If you can come up with a solution, please do so. The best course of action would be to look through all evaluations and swap *everything* that isn't already using `LazyNumber`s to that, but that's quite a piece of work. More unit tests for that would also be nice.

I'd love to do that, but I'm *very* short on time currently, that won't change for the next few months. So if you can come up with something, please do so and I'll happily review and test it.

**Comment by binbinvn** [comment]
I met same problem
