### ISSUE TITLE
Negative Base Doesn't Give Correct Result

### ISSUE THREAD

**Issue by NumberC** [ezylang/EvalEx#231]
If you pass `"-2^2"` into an expression, you get 4. The result should be -4 because the -2 isn't in paranthesis. As it is right now, it's the same as "-(2^2)" which will return -4. If you add paranthesis, it should return "(-2)^2".

**Comment by uklimaschewski** [comment]
The square of -2 is 4, isn't it? -2 * -2 is 4.

**Comment by NumberC** [comment]
No. -2^2 is seen as -(2^2) which equals -4. What you're thinking is (-2)^2.

**Comment by uklimaschewski** [comment]
After googling around, I came across this interesting list from the elm project on github. It seems that there is no real standard on how to handle precedence and associativity in this case. There are even different results on different types of TI pocket calculators.
See https://github.com/elm/compiler/issues/1530 for a more complete discussion.

What | Code Tested | Result | First Step
-- | -- | -- | --
Elm | -2^2 | 4 | negation
Bash | -2**2 | 4 | negation
DuckDuckGo | -2^2 | 4 | negation
Excel | -2^2 | 4 | negation
EtherCalc | -2^2 | 4 | negation
Fortran | -2**2 | -4 | exponentiation
Google | -2^2 | -4 | exponentiation
Google Sheets | -2^2 | 4 | negation
Handheld Calculators | -2^2 |   | Varies
Lua | -2^2 | -4 | exponentiation
Matlab | -2^2 | -4 | exponentiation
Octave | -2^2 | -4 | exponentiation
Perl | -2**2 | -4 | exponentiation
PostgreSQL | -2^2 | 4 | negation
Python | -2**2 | -4 | exponentiation
Ruby | -2**2 | -4 | exponentiation
Tcl | -2**2 | 4 | negation
WolframAlpha | -2^2 | -4 | exponentiation

**Comment by NumberC** [comment]
Should that be an option? Allow users to determine how they want the exponents to work?

**Comment by uklimaschewski** [comment]
Yes, I think that could be a way. I will mark this as an enhancement.

**Comment by uklimaschewski** [comment]
Fixed with #237
