### ISSUE TITLE
Provide TRUE and FALSE as public static LazyNumbers

### ISSUE THREAD

**Issue by mmorrisontx** [ezylang/EvalEx#265]
Implementing custom boolean LazyFunctions is a bit annoying at the moment, because each function (or project) needs to maintain its own copy of ONE and ZERO (similar to the [example](https://github.com/uklimaschewski/EvalEx#custom-functions-with-string-parameters)).

If EvalEx exposed a public LazyNumber instance for TRUE and FALSE (or ONE and ZERO?), it would make implementing custom LazyFunctions trivial, and in most cases they could just be a lambda.

**Comment by mmorrisontx** [comment]
Alternatively, an abstract implementation of LazyFunction which needed a `long lazyEval(lazyParams)` rather than a `LazyNumber lazyEval(List<LazyNumber> lazyParams)`, would also solve the problem.

**Comment by uklimaschewski** [comment]
Obsolete with version 3
