### ISSUE TITLE
Unexpected Exceptions

### ISSUE THREAD

**Issue by GoldenGnu** [ezylang/EvalEx#266]
If you use EvalEx with user input you will get a lot of unexpected exceptions.
I expect `ExpressionException`, but, a lot of other exceptions are thrown as well.
Making it very hard to handle safely when you're implementing EvalEx.

Here are some test cases to showcase some of the examples:
```java
import com.udojava.evalex.Expression;
import org.junit.Test;


public class ExpressionExceptionTest {

	@Test
	public void testNullPointerException() {
		Expression expression = new Expression("\"");
		expression.eval();
	}

	@Test
	public void testStringIndexOutOfBoundsException() {
		Expression expression = new Expression("100\"");
		expression.eval();
	}

	@Test
	public void testArithmeticException() {
		Expression expression = new Expression("100/0");
		expression.eval();
	}

	@Test
	public void testNumberFormatException() {
		Expression expression = new Expression("1.0.");
		expression.eval();
	}

	@Test
	public void testExpressionException() {
		Expression expression = new Expression("");
		expression.eval();
	}
	
}

```
My suggestion would be to wrap those exceptions in `ExpressionException` exceptions, ensuring easy exception handling.
It may even be viable to change ExpressionException from a `RuntimeException` (unchecked exception) to an `Exception` (checked exception), declaring what methods can throw it.

**Comment by uklimaschewski** [comment]
Obsolete with version 3, there should be only 2 exceptions now. ParseException an EvaluationException, each with detailed information.
