### ISSUE TITLE
how to set the scale like BigDecimal

### ISSUE THREAD

**Issue by Rocky-Hu** [ezylang/EvalEx#283]
```
 Expression expression = new Expression("a- b");
        expression
                .with("a","480.70")
                .and("b","480.99");
BigDecimal c=  expression.eval();
```
The result is  -0.29. I want is **-0.290**, and set the precision is not working. 

like BigDecimal:

```
BigDecimal a= new BigDecimal("480.70");
BigDecimal b= new BigDecimal("480.99");
BigDecimal c= a.subtract(b).setScale(3);
```
Is there any way ?

**Comment by RobertZenz** [comment]
Yes, `eval()` strips the zeroes f the `BigDecimal` result by default. However, you missed that there is the `eval(boolean)` overload which allows you to disable that behavior.

**Comment by uklimaschewski** [comment]
With version 3, stripping trailing zeroes can be configured, but I see that it isn't in the documentation. 
Leaving this open, though it is fixed to remind adding the documentation.

**Comment by uklimaschewski** [comment]
Documentation is here: https://ezylang.github.io/EvalEx/configuration/configuration.html
