### ISSUE TITLE
Three new features for evalex

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [ezylang/EvalEx#290]
Hello @uklimaschewski. I am android developer and  i used your library in calculator app for android. Also i want rewrite app,which build sound graphic of function,using your library. But i want suggest three features for your lib.

At first,i want,what you add feature,which allow to set several values for variable. For example i want to build graphic of function f(z) = x^2 + y^2 (x from 0 to 1000,y from 0 to 500) whith step 1. So,for x we have 1001 values,because 1000 we include,and for why 501 values,because 500 we include. so,for now to do this,we should parse the same expression 1001*501 so 501501 times,instead of parsing one time,and applying of ready stack for all values,which will increase performance in several times. So,please add feature,which allow to set arrayList of values for each variable,because i could set any values for each variable,therefore adding new arguments,such as range from,range to and stepp for each variable will limited this feature,so it should be arrayList or array of values,which i can set independent for each variable.

Second feature,which i want to have,it setting definition scope for operator and function. For example user in my app imput expression sqrt(x) in range -1000,1000 with step 0.1. For now,i catch this situation via try/catch,but in this case i have a problems with performance,because,at first,we have first problem,about which i wrote above,and at second we check all values for this function,but sqrt function define only from 0 to + infty as,for example,x^(1/integer even value). Or function x^x defined in any values,except 0,because 0^0 is undefined. So for functions and operators should be added method,which allows to find,whether some function or operator define in this dot. Yes,i understand,what it's very difficult,but i agree override this method for each function myself,so please add this feature,because to get scope of definition to some function or operator,i should parse expression myself,to get subfunctions inside a dificult function,but i want avoid this,therefore  i use your library.

Third feature,which i want to have,it's exeact result,when we have a fraction as a result. Probably you need add special class for this. For example for expression 4/6 i expect get object,which shows,what we have 0 integers,numerator 2 and denominator 3 or,if i dont want to use fraction reduction (it should be optional) it should be return object whith 0 integers with numerator 4 and denominator 6. Similar result should be for expression 11/6-2/3. For this case we should have object,with 1 integer ,numerator 1 and denominator 6 (7/6 it's 1 1/6). All another operations and functions with ordinary fractions should be added too. All returns objects of class fraction (idea of name for class,in which we will have all parts of fraction) should be bigDecimal,because we can have very long fractions.

I hope,what you will add this features,or at least part of them. Thank you very much for your library.

**Comment by uklimaschewski** [comment]
Hello @AlexandrKozlovskiy,

To answer your questions:
1) Once the expression is parsed, the parsed result (RPN list) is cached and re-used o each subsequent evaluation.
Therefore, you can use loops for variable values outside of EvalEx without a performance impact.
Just make sure, that the expression is re-used:
```java
Expression expression = new Expression("a*2);
for (int i = 0; i < 10; i++)
    BigDecimal result = expression.with("a", BigDecimal.valueOf(i)).eval();
```

2) The parameter value for a function is only known when it comes to evaluation. During "design time", it is unknown and therefore can't be validated. The check for correct parameter values is clearly part of the function itself, because different implementation may have different constraints. Also, defining a simple min/max for a parameter might not be enough.
I do not see how to implement a generic validation here.
Version 3 of EvalEx (currently in work) will have a parameter definition structure for functions, which may allow some basic validation in the future.

3) A main feature of EvalEx is to use BigDecimal for calculation. I do not see a way to implement an optional "fraction-reduction-less" calculation like you proposed.

**Comment by AlexandrKozlovskiy** [comment]
1. It very good,what you reuse instance of expression,i mean,not reparse expression,because i not learned sources of your library enough. I may be will check it,to be sure in it.
2. Yes,it impossible get exact difinition scope for some functions,for example for function x^x,where x < 0,but for some functions and operators we can do it,e.g sqrt(x) or x^1/n,where n is even number. For this functions we know,what it define from 0 to +infty. Or we can do it for operator /,because we know,what it define for all values except zero. But problem will hapend,when we want to get difinition scope,but,i hope,it can be solved. For example difinition scope for function sqrt(1/x)  is from 1 to +infty,because sqrt define from 0 to +infty,and / operator define in any value,except 0. So,if it possible compute exact definition scope for some functions,which we have in expression,it should be return joined definition of function for all expression. Probably it should be special class for it. Yes,i understand,what it's very dificult to do this,but,in my opinion,algorithm for this is not so dificult. at first we should take start and end values of scope definition for all functions and operators,which we have in our expression,and which we can compute. At second we should take the greatest value of start value,and smallest value for end value. After doing it for two functions or operators,we should compare this value for third function or operator,and do the same selection. We can compare value of definition of scope not only between functions and operators separately,but,for example,between function and operator. For some functions we can have several definitions of scope,so for each function and probably for whole expression,it should be returns list of objects of some class,which connected with some definition scope. E.g for / operator we have two objects of our class,because we have two scope definition (from 0 to infty and from -infty to 0). In two cases 0 not in interval. But i haven't idea how to compute scope definitions for whole expression,if at least one function or one operator have several scope definitions. It it difficult for you understand my idea and/or develop algorithm,you can add method,which allow to get list of definition scopes for each function and operator in this expression. Please also add feature,to user,if it want,can set definition scopes for existing or new functions and operators.
3. About ordinary fraction,it seems it not dificult. At first,as i wrote before,you should create special class for it,e.g class fraction. Probably method of class expression eval should return not bigDecimal,but fractions even for integers,with numerator and denominator 0 for integers. to get ordinary fraction we should override / operator and get not only devision,but mode. and write this mode as numirator and the second value as denominator. e.g 14/6 have two integers. It have also mode 2,so in fraction object for integer we have 2,for numerator we have 2 and for denominator 6. To do reduction of fraction we should get greatest common divisor. Algorithms to define it in my opinion are not dificult. After computin of greatest common divisor (for 2 and 6 it 2),we should devide numerator and denominator on it,so in numerator we have 1 and in denominator we have 3. All object of class fraction,as i wrote,should be bigDecimal.

**Comment by uklimaschewski** [comment]
Closing this with version 3. Re-open, or better, create a new issue if there is more discussion needed. Consider using the discussion area, instead of the issue management, though.
