### ISSUE TITLE
How do I get declared variables in version 3?

### ISSUE THREAD

**Issue by VincentJoshuaET** [ezylang/EvalEx#317]
I use it to show an error when there is no value/constant for any declared variable in an expression string.

**Comment by uklimaschewski** [comment]
There is this method:
```Java
  /**
   * Returns all variables or constants that are used i the expression, excluding the standard
   * constants like e.g. <code>PI</code> or <code>TRUE</code> and <code>FALSE</code>.
   *
   * @return All used variables and constants less the standard constants.
   * @throws ParseException If there were problems while parsing the expression.
   */
  public Set<String> getUsedVariables() throws ParseException;
```

**Comment by VincentJoshuaET** [comment]
> There is this method:
> 
> ```java
>   /**
>    * Returns all variables or constants that are used i the expression, excluding the standard
>    * constants like e.g. <code>PI</code> or <code>TRUE</code> and <code>FALSE</code>.
>    *
>    * @return All used variables and constants less the standard constants.
>    * @throws ParseException If there were problems while parsing the expression.
>    */
>   public Set<String> getUsedVariables() throws ParseException;
> ```

In version 2.x, `getUsedVariables` and `getDeclaredVariables` are different. Used variables are variables inside the expression string. Declared variables are variables that we input with `with` or `and`. They may or may not be equal.

**Comment by VincentJoshuaET** [comment]
https://github.com/ezylang/EvalEx/blob/2.x/src/main/java/com/udojava/evalex/Expression.java

```
/**
   * Exposing declared variables in the expression.
   *
   * @return All declared variables.
*/
public Set<String> getDeclaredVariables() {
    return Collections.unmodifiableSet(variables.keySet());
}
```

```
/**
   * Returns a list of the variables in the expression.
   *
   * @return A list of the variable names in this expression.
   */
  public List<String> getUsedVariables() {
    List<String> result = new ArrayList<String>();
    Tokenizer tokenizer = new Tokenizer(expressionString);
    while (tokenizer.hasNext()) {
      Token nextToken = tokenizer.next();
      String token = nextToken.toString();
      if (nextToken.type != TokenType.VARIABLE || DEFAULT_CONSTANTS.containsKey(token)) {
        continue;
      }
      result.add(token);
    }
    return result;
}
```

**Comment by uklimaschewski** [comment]
There are two possibilities.
One is to write an own data accessor that allows you to also control the declared variables.
Or you could code it like this, checking the data accessor for each used variable:
```Java
  void checkVariables() throws ParseException {

    Expression expression = new Expression("a+B*b-A/PI*(1/2)*pi+e-E+a").with("a", 12);

    DataAccessorIfc dataAccessor = expression.getConfiguration().getDataAccessorSupplier().get();

    for (String variable : expression.getUsedVariables()) {
      if (dataAccessor.getData(variable) == null) {
        System.out.println("Variable not declared: " + variable);
      }
    }
  }
```

**Comment by VincentJoshuaET** [comment]
Will it not be possible for a straightforward method anymore like in 2.x?

**Comment by uklimaschewski** [comment]
Sure is this possible, but why not a method that directly returns the *undeclared* variables? e.g. `public Set<String> 
 getUndeclaredVariables()` ?

**Comment by VincentJoshuaET** [comment]
Yeah that would work too!
