### ISSUE TITLE
java.lang.AssertionError: annotation container = @com.ezylang.evalex.functions.FunctionParameters()annotation element class = interface com.ezylang.evalex.functions.FunctionParameter; missing value() method

### ISSUE THREAD

**Issue by VincentJoshuaET** [ezylang/EvalEx#340]
What should I add in the ProGuard rules to fix this?

**Comment by uklimaschewski** [comment]
You should exclude EvalEx  (package com.ezylag.evalex) from ProGuard, as this is a open source library anyways.
It makes absolutely no sense to obfuscate open source libraries. Anybody who wants to see the original source code, can do this here.
How to exclude certain packages or libraries is a question you should ask the makers of ProGuard. There are also some online resources you can google for.

**Comment by uklimaschewski** [comment]
Without testing it, this should work if you add it to your proguard.config:
```
-keep class com.ezylag.evalex.** { *; }
-dontwarn com.ezylag.evalex.**
```

**Comment by VincentJoshuaET** [comment]
This is what's only needed:
`-keep @interface com.ezylang.evalex.functions.FunctionParameters { *; }`
