### ISSUE TITLE
ShuntingYardConverter silently drops tokens

### ISSUE THREAD

**Issue by Maxr1998** [ezylang/EvalEx#345]
A nonsensical expression like `Test 2 + 2 2 + 3` which is correctly tokenized as
```
[
    Token(startPosition=1, value=Test, type=VARIABLE_OR_CONSTANT),
    Token(startPosition=6, value=2, type=NUMBER_LITERAL),
    Token(startPosition=8, value=+, type=INFIX_OPERATOR),
    Token(startPosition=10, value=2, type=NUMBER_LITERAL),
    Token(startPosition=12, value=2, type=NUMBER_LITERAL),
    Token(startPosition=14, value=+, type=INFIX_OPERATOR),
    Token(startPosition=16, value=3, type=NUMBER_LITERAL),
]
```
is converted by the `ShuntingYardConverter` to the syntax tree of
```json
{
  "type": "INFIX_OPERATOR",
  "value": "+",
  "children": [
    {
      "type": "INFIX_OPERATOR",
      "value": "+",
      "children": [
        {
          "type": "NUMBER_LITERAL",
          "value": "2"
        },
        {
          "type": "NUMBER_LITERAL",
          "value": "2"
        }
      ]
    },
    {
      "type": "NUMBER_LITERAL",
      "value": "3"
    }
  ]
}
```

This drops and ignores multiple tokens and incorrectly causes the expression to evaluate to `7`.
Instead, this expression should fail at some place because it isn't evaluable.

**Comment by RobertZenz** [comment]
I believe that is implicit multiplication at work.

```
Test 2 + 2 2 + 3
   0 2 + 2 2 + 3
   0*2 + 2*2 + 3
   0   +  4  + 3 = 7
```

Basically, but seems like the first one is dropped somewhen before the actual evaluation because the variable is not set.

**Comment by Maxr1998** [comment]
I don't think that's the case. An unset variable should error out, but it doesn't because it's already dropped before the abstract syntax tree is evaluated.

Another example: `2 3 + 4` evaluates to 7, which completely ignores the 2. If it was implicit multiplication, it should result in 9.

**Comment by RobertZenz** [comment]
That's true, then I'm out of ideas.

**Comment by HSGamer** [comment]
`Test World` would become `{"type":"VARIABLE_OR_CONSTANT","value":"World"}`
`Test World Hello` would become `{"type":"VARIABLE_OR_CONSTANT","value":"Hello"}`
`Test World 1` would become `{"type":"NUMBER_LITERAL","value":"1"}`

So, same issue I guess.

**Comment by HSGamer** [comment]
After debugging some nonsense & evaluable strings, I think the culprit is in this line
https://github.com/ezylang/EvalEx/blob/9c789077182b4b0f143e73f7090164ca771cdbed/src/main/java/com/ezylang/evalex/parser/ShuntingYardConverter.java#L115

When I try the normal expressions, the `operandStack` size is mostly `1` so it'll take the whole tokenized node.
However, when I try the nonsense strings, the `operandStack` size is higher than `1` (`Test 2 + 2 2 + 3` would be `3`) and the line would take the last node in the stack.

I think we should include another exception check when `operandStack` is higher than `1` after the Shunting Yard conversion.

**Comment by Maxr1998** [comment]
When looking at it quickly back then, I also noticed this. There may be some use case if you use functions with multiple parameters. You could try how it behaves for an `if` call for example.

**Comment by HSGamer** [comment]
> When looking at it quickly back then, I also noticed this. There may be some use case if you use functions with multiple parameters. You could try how it behaves for an `if` call for example.

It's verified that the size is also `1` (`IF(5 + 2 > 3, 5 + 2, 2 + 3) + FLOOR(11.2)`).
I'll make a PR and wait for the owner to reply further more.

**Comment by Maxr1998** [comment]
Thanks for the fix and merge! Will there be a patch release with this fix applied in the near future?

**Comment by uklimaschewski** [comment]
I plan a release after some more issues are fixed, will be soon.

**Comment by Maxr1998** [comment]
Alright, no rush, thanks for the info though!
