### ISSUE TITLE
Caching of parsed evaluation and subtree

### ISSUE THREAD

**Issue by barnhill** [ezylang/EvalEx#355]
Is there any plan to support caching of the parsed expression for repeat evaluations of the same expression with different variable values to avoid the parsing and subtree building again?

**Comment by bilfash** [comment]
You can maintain your own caching before calling this library.

**Comment by uklimaschewski** [comment]
The AST of a parsed expressions are already cached. Subsequent evaluations of an expression with different values do not parse the expression again.
