### ISSUE TITLE
Evaluation of asin(1.5) will throw NumberFormatException which is a bit misleading

### ISSUE THREAD

**Issue by 42i** [ezylang/EvalEx#361]
This will throw a NumberFormatException:
```
      EvaluationValue v = new Expression("asin(a / b)")
          .with("a", 3.0)
          .with("b", 2.0)
          .evaluate();
```
Should it not rather throw an EvaluationException?

**Comment by uklimaschewski** [comment]
Thank you very much for the bug report. Version 3.0.3 of EvalEx has been released and fixes this bug.
