### ISSUE TITLE
Structure access with arbitrary key format

### ISSUE THREAD

**Issue by namero999** [ezylang/EvalEx#368]
Hello, really loving this little library.

I'm facing the issue where my context is as follows

```json
{
    "element": {
        "a prop": 1
    }
}
```

and I wish I could write an expression such as `element['a prop']` or `element.'a prop'`. Is there a way to achieve this?

**Comment by namero999** [comment]
I've just randomly found out that `element."a prop"` (double quotes) work. I think this is an interesting use case to surface in the documentation.

**Comment by uklimaschewski** [comment]
What a nice finding!
To be honest, this feature wasn't intentional. But looking quickly at the code, yes, it works like it was intentional. 😉 
I'll have a deeper look into it, write some tests and add it to the documentation.
Thanks again for finding this nice easter egg. 🙃🙂

**Comment by namero999** [comment]
Ahahah I figured! was checking the code too. Funny.

But I think it's a reasonable "requirement" and it'd be great to specify the correct syntax and acknowledge it in tests as you say, yes.

Currently the only drawback is the requirement for parenthesis in the case of lists. I think it would be more intuitive if it were `element."a prop"[0]`, since `element.prop[0]` would work just fine.

**Comment by uklimaschewski** [comment]
Thanks again for the finding.
I have added some tests and documentation.
Also the fix for the quoted element name i combination with arrays was quite easy.
Expressions like `a."prop b"[0]."prop c"` will work now.

**Comment by namero999** [comment]
That's nice! Thanks for the fast turnaround on this!
