### ISSUE TITLE
OutOfMemoryError/memory leak on `e.<number>` input

### ISSUE THREAD

**Issue by Maxr1998** [ezylang/EvalEx#374]
Running the following code causes my Android app the memory usage to rise rapidly until it is interrupted or crashes.

```kotlin
val ex = Expression("e.1")
ex.evaluate()
```

It's reproducible on both 3.0.4 and 3.0.3, I haven't checked any other versions. In the debugger I noticed that the `Tokenizer.tokens` list is seemingly the culprit, containing thousands of `NUMBER_LITERAL` entries with value set to an empty string.

**Comment by uklimaschewski** [comment]
Hi, I would expect this to produce a parsing error before trying to evaluate.
