### ISSUE TITLE
Consider some wildcards for `Map<String, Object> values`

### ISSUE THREAD

**Issue by JanecekPetr** [ezylang/EvalEx#375]
The method `public Expression withValues(Map<String, Object> values)` and all its derivatives using `Map<String, Object>` could maybe use some wildcards. In our case, we have a `Map<String, Double>` as we only provide numbers for variables. However, we can't pass such a map into EvalEx because it doesn't accept it.

**Comment by uklimaschewski** [comment]
You mean something like that?
```java
  public Expression withValues(Map<String, ?> values) {
    for (Map.Entry<String, ?> entry : values.entrySet()) {
      with(entry.getKey(), entry.getValue());
    }
    return this;
  }
```

this should be also backward compatible for source and binary.

**Comment by JanecekPetr** [comment]
I think so, yes! I wasn't sure whether this breaks someting internally as I haven't dug very far inside. Regarding compatibility, I think this is indeed one of the only backward compatible changes available.
