### ISSUE TITLE
Unsupported data type 'java.time.LocalDate'

### ISSUE THREAD

**Issue by CostaVita** [ezylang/EvalEx#378]
This code throws `java.lang.IllegalArgumentException: Unsupported data type 'java.time.LocalDate'`
```
        Map<String, Object> testMap = new HashMap<>();
        testMap.put("rate", 2);
        testMap.put("tax", 3);
        testMap.put("date", LocalDate.now());

        Expression expression = new Expression("currentElement.rate + currentElement.tax");
        expression.with("currentElement", testMap);

        BigDecimal numberValue = expression.evaluate().getNumberValue();
```

Why this happens is not clear, I do not use `date` field in the formula `"currentElement.rate + currentElement.tax"`

**Comment by uklimaschewski** [comment]
Hi, the conversion of the map values happens even before they are used in the formula.
