### ISSUE TITLE
Bundle Proguard Rules

### ISSUE THREAD

**Issue by vanniktech** [ezylang/EvalEx#391]
You can do so by creating a resource file at: `src/main/resources/META-INF/proguard/evalex` which contains the following:

```
-dontwarn lombok.Generated
```

Here's an example with RxJava: https://github.com/ReactiveX/RxJava/blob/216f509083efdd01b4a36108df3a3a7ac45f0d0c/src/main/resources/META-INF/proguard/rxjava3.pro

Otherwise when using this library on Android it fails:

```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/niklas/dev/GitHub/vanniktech/app-game-utilities/build/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class lombok.Generated (referenced from: boolean com.ezylang.evalex.config.ExpressionConfiguration$ExpressionConfigurationBuilder.allowOverwriteConstants$set and 108 other contexts)

FAILURE: Build failed with an exception
```

**Comment by uklimaschewski** [comment]
Thanks, I will add this to the next release.

**Comment by uklimaschewski** [comment]
@vanniktech can you please have a look at my pull reuest #394, if this is ok for you?

**Comment by uklimaschewski** [comment]
Ah,  thanks for the review. Missed the dot. I have corrected it.

**Comment by vanniktech** [comment]
@uklimaschewski Has reflection or something runtime related been added in the last versions? Version 3.4.0 no longer works on Android when using R8 (Code shrinking), if so we should also add the proper rules such that R8 knows what can be shrinked/removed and what not. My workaround for now is to `-keep class com.ezylang.evalex.** { *; }` but this is way to much.
