### ISSUE TITLE
decimalPlacesRounding has confusing behavior

### ISSUE THREAD

**Issue by agronick** [ezylang/EvalEx#401]
I was stuck on this bug for a while. I had `decimalPlacesRounding(0)` because I wanted whole numbers in the result. What I didn't expect is for it to take the decimals out of all the numbers that were hard coded in the equation.

I think one of the following should be done:
- Make `decimalPlacesRounding` only apply to the result (preferred) 
- Add a new function that only applies to the result without wrapping everything in `ROUND(x,0)`
- Make the documentation clear that `decimalPlacesRounding` applies to every single number and intermediary result

**Comment by uklimaschewski** [comment]
This is not a bug, but working as intended and also documented in [Precision, Scale and Rounding](https://ezylang.github.io/EvalEx/concepts/rounding.html#configuring-precision-rounding-mode-and-automatic-scaling):

> Automatic scaling is disabled by default. When enabled, EvalEx will round all input variables, intermediate operation and function results and the final result to the specified number of decimal digits, using the current rounding mode

I will copy this documentation also to the JavaDoc, so it is clearer there, too.

Adding another option to do rounding only for the final result is a good idea, I will add one to the 3.1.0 release.

**Comment by agronick** [comment]
Yeah I understand it is working as intended but I'm not sure why someone would choose to have less accuracy I'm their equation rather than just using this for formatting. I know there isn't a desire to break backwards compatability but this was a confusing issue to solve.

**Comment by uklimaschewski** [comment]
This is a common practice in financial applications. It is similar to what you have on most desktop calculators. A switch where you can select the rounding mode. Usually "F" for floating point/no rounding, "0", "2", "3" for zero, two or three decimal places. It will round each operation then.
If you don't do it that way, your sum may not be consistent with the individual parts of the calculation.

**Comment by agronick** [comment]
That makes sense.

**Comment by agronick** [comment]
The main issue is that I want the user to be able to return strings and have the option to convert to a whole number. So I need to format after the fact and catch the exception if the formatting fails because their expression returns something besides a number.
