### ISSUE TITLE
OutOfMemoryError: for wrong expression with 2 dots 

### ISSUE THREAD

**Issue by danielpeintner** [ezylang/EvalEx#412]
I have some *old* testing code using EvalEx@2.7. Out of curiosity I wanted to try whether using the new 3+ version might work for my test-set. 

In the old test set the following expression `"1..0*2.7*195.0"` simply returns `null`/failure.

EvalEx@3.1.0 runs into an `OutOfMemoryError `which most likely shouldn't happen even though the expression is surely wrong. 

All the best and thanks for your work and EvalEx in the first place 👍

**Comment by uklimaschewski** [comment]
Thanks for finding and reporting this bug!
