### ISSUE TITLE
Support arrays as function parameters

### ISSUE THREAD

**Issue by QuantumJigsaw** [ezylang/EvalEx#414]
In some cases functions can receive arrays so it would be helpful if it was supported.

**Comment by uklimaschewski** [comment]
Hi, can you g into more detail? What should be supported?
Arrays (and also structures) can be be parameters to functions already.

**Comment by uklimaschewski** [comment]
I see what you mean, there was a similar discussion about supporting a date-time data values using literals.
For date-time and duration, we introduced constructor functions, e.g. `DT_DATE_NEW(2023, 12,4)`, to create a new date type.
Similar could be very easily done with a constructor function for arrays, e.g. `ARR_NEW(1,2,3,4)`, or `ARR_NEW("A", "b", "C")`.

Supporting array literals would be much harder to implement, probably only possible with a new major version release of EvalEx.

What do you think of that possibility?

**Comment by QuantumJigsaw** [comment]
@uklimaschewski Maybe I have the wrong idea but what I would expect to happen was for the array to get flatten as function parameters.

E.g.

`FUNCTION([1,2])`

Node:

- Token: FUNCTION
- Parameters: 1, 2

So the only thing that would need to be update was the Shunting Yard as from there the array would be threated as multiple literals.

**Comment by uklimaschewski** [comment]
Bu then the function would not receive an array as a parameter, but multiple parameters.
Imagine you would want to write a function that adds two arrays, element by element, and return the resulting array:
`ARR_ADD([1,2,3], [4,5,6])`
That would result into `ARR_ADD(1,2,3,4,5,6)`, which is not what you would expect.

**Comment by QuantumJigsaw** [comment]
You are right. 

I think then I will use a custom function
