### ISSUE TITLE
problem with placeholder

### ISSUE THREAD

**Issue by lebarov** [ezylang/EvalEx#418]
hello dear readers this issue,
im making a minecraft server, and im need to use placeholder "Math", when i downloaded it by "papi ecloud download Math", i must to reload a plugin, and when i wrote "papi reload", i get a error message:

`[21:09:54 ERROR]: [PlaceholderAPI] Failed to load class files of expansion.
java.util.concurrent.CompletionException: java.lang.UnsupportedClassVersionError: com/ezylang/evalex/EvaluationException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

sorry for my english ;)

**Comment by uklimaschewski** [comment]
EvalEx needs minimum Java Version 11 (class file version 55).
You are using Java 8 (class file version 52).
You need to upgrade your Java.
