### ISSUE TITLE
SQRT function doesn't work

### ISSUE THREAD

**Issue by ChemFlix** [ezylang/EvalEx#423]
This is the used placeholder:
%math_SQRT((%var_block_z%-%var_player_z%)*(%var_block_z%-%var_player_z%))%

Thats the error in the console:
```
! [Wed 15:21:42 WARN  PlaceholderAPI] [math] Invalid Placeholder detected!
! [Wed 15:21:42 WARN  PlaceholderAPI] [math] Placeholder: %math_SQRT((%
! [Wed 15:21:42 WARN  PlaceholderAPI] [math] Cause:       'SQRT((' is not a valid Math expression.
```

The Math Extension is on the latest version on PAPI 2.11.5

**Comment by uklimaschewski** [comment]
Hi, I think you reached the wrong repository.
I think you should ask your question at the the [PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI) project.

EvalEx knows nothing about those patterns you mentioned.

**Comment by ChemFlix** [comment]
Oh, I'm sorry. I will contact PAPI support. Still, thank you ^^
