### ISSUE TITLE
Equals/NotEquals operator is now sometimes showing inconsistent behavior

### ISSUE THREAD

**Issue by stevenylai** [ezylang/EvalEx#428]
Related the change from : https://github.com/ezylang/EvalEx/pull/421 where we switched from `equals` to `compareTo`

Now for the below 2 expressions:
1.  `a == ""`
2.  `"" == a`

If evaluated with `a = 0`, first one will return `true` because left side is a number, and `EvaluationValue.compareTo` will attempt to convert the right side to a number value as well, and as long as string is not a valid boolean, it will be converted to `0`. Likewise, when left side is string, right side will also be converted to a string hence 2 returns `false`

Before the change the 2 expressions above are both `false` which seems to make more sense to me. Perhaps we need to check type for the operator?

**Comment by uklimaschewski** [comment]
Than you for finding this.
I think the best way is to stay backward compatible and simply make the equals/not equals operator check the types.
If they differ, the operands are not equal.
