### ISSUE TITLE
does not evaluate if expression operand has a period, hyphen seperater

### ISSUE THREAD

**Issue by Manan-13** [ezylang/EvalEx#494]
"{airQuality.temperature} > 44"

Map<String, Object> values = new HashMap<>();
values.put("a-b", "indoor"); 
EvaluationValue result = e.withValues(values).evaluate();

BaseException(startPosition=4, endPosition=5, tokenString=a, message=Variable or constant value for 'a' not found)
	at Main.main(Main.java:24)
Caused by: BaseException(startPosition=4, endPosition=5, tokenString=a, message=Variable or constant value for 'a' not found)

Any workaround for this ?

**Comment by stevenylai** [comment]
dot (`.`) and hyphen (`-`) are reserved operators from the library. I would suggest you replace those special characters with underscore (`_`) when creating expressions and passing in variables.

**Comment by uklimaschewski** [comment]
Closing this, we won't support special characters apart from underscore in variable names.
