### ISSUE TITLE
Function Average has a bug

### ISSUE THREAD

**Issue by IrvingYuanStu** [ezylang/EvalEx#499]
Expression expression = new Expression("AVERAGE(data)");
        List<Integer> list = List.of(2, 4, 6);
        Double result = expression.with("data", list).evaluate().getNumberValue().doubleValue();
        System.out.println(result);

**Comment by uklimaschewski** [comment]
The `AVERAGE` function doesn't support arrays as input parameter(s).
I'll mark this as an enhancement.

**Comment by oswaldobapvicjr** [comment]
I can implement this enhancement.
